#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
mvn exec:exec -DlocalRepository=$OPENSHIFT_DATA_DIR\.m2\localRepository -f $OPENSHIFT_REPO_DIR/cs2013/pom.xml exec:exec -Dbind=$OPENSHIFT_INTERNAL_IP -Dport=8080 -X>  $OPENSHIFT_HOMEDIR/diy-0.1/logs/server.log 2>&1 &
